### ISSUE TITLE
https

### ISSUE THREAD

**Issue by crisward** [Sija/raven.cr#12] opened 2017-03-19 00:23 UTC
Has this been tested with https ?
My sentry server has ssl, and I'm getting the following error from the failure_callback - 
```
ERROR -- sentry: Unable to record event with remote Sentry server (Raven::Error - Moved Permanently): 0x944245: ??? at /app/lib/raven/src/raven/transports/http.cr 64:11
```
I'm pretty sure this happens when traffic is redirected from http, to https? Just a guess though as I've not read the source.

**Comment by Sija** [comment] 2017-03-19 02:51
Stupid question, but did url in `SENTRY_DSN use `https` scheme?

**Comment by crisward** [comment] 2017-03-19 07:42
It's not a stupid question, but yes I used https:// in my DSN. I'll try adding logger.level.

**Comment by Sija** [comment] 2017-03-20 04:46
I think I've found the culprit. Could you please try [`develop`](https://github.com/Sija/raven.cr/tree/develop) branch and see does it work?

**Comment by crisward** [comment] 2017-03-20 08:24
Will do, thanks.

**Comment by crisward** [comment] 2017-03-20 08:35
Thanks. That worked.

**Comment by crisward** [comment] 2017-03-20 08:40
Also, with my test error I got this. I'm using sentry 8.05 (I installed in a while ago, possibly due an update)

![screen shot 2017-03-20 at 08 39 21](https://cloud.githubusercontent.com/assets/3109157/24092847/c7c05188-0d48-11e7-9d62-8c895cadcab9.png)

**Comment by Sija** [comment] 2017-03-20 16:44
gr8! i'm closing this issue and will release patched version soon, in the meantime you can stick to `develop` branch.

**Closed by Sija** 2017-03-20 16:44 UTC

**Comment by Sija** [comment] 2017-03-20 16:46
Regarding the errors, they're caused by the fields added l8r on to the Sentry server API. These error messages are harmless, yet you might miss OS information section (See https://docs.sentry.io/clientdev/interfaces/contexts/).
