### ISSUE TITLE
Error with the Lucky implementation

### ISSUE THREAD

**Issue by wout** [Sija/raven.cr#66] opened 2020-05-27 12:30 UTC
When I include raven, my Lucky app fails to compile with the following error:

```cr
Module validation failed: Function return type does not match operand type of return inst!
  ret %"(Array(AnyHash::JSONTypes::Value)+ | Bool | Float32 | Float64 | Hash(String | Symbol, AnyHash::JSONTypes::Value) | Int128 | Int16 | Int32 | Int64 | Int8 | JSON::Any | Set(AnyHash::JSONTypes::Value) | String | Symbol | Time | UInt128 | UInt16 | UInt32 | UInt64 | UInt8 | Nil)" %1, !dbg !21
 %"(Array(AnyHash::JSONTypes::Value) | Bool | Float32 | Float64 | Hash(String | Symbol, AnyHash::JSONTypes::Value) | Int128 | Int16 | Int32 | Int64 | Int8 | JSON::Any | Set(AnyHash::JSONTypes::Value) | String | Symbol | Time | UInt128 | UInt16 | UInt32 | UInt64 | UInt8 | Nil)" = type { i32, [3 x i64] } (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

I already reported this at the Crystal repo, but do you have an idea how to work around this? I believe it has something to do with `AnyHash`. You probably know better where to look.

**Comment by Sija** [comment] 2020-05-27 20:19
Looks like https://github.com/crystal-lang/crystal/issues/6253

**Comment by Sija** [comment] 2020-05-27 20:57
Duplicate of #49

**Closed by Sija** 2020-05-27 20:57 UTC
